source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, "10.0"

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

target "imystery" do

    #pod 'RealmSwift'            
    pod 'Alamofire'
    pod 'SnapKit'
    pod 'IQKeyboardManagerSwift'
    #pod 'ChameleonFramework/Swift'
    pod 'Moya'
    pod 'SwiftyJSON'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    pod 'UINavigationItem+Margin'

    pod 'MBProgressHUD'
    pod 'DZNEmptyDataSet'
    pod 'Bugly' 
    pod 'YYKit'
    pod 'MJRefresh'
    
    pod 'UMCCommon'
    pod 'UMCPush'
    pod 'UMCSecurityPlugins'

end


